# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI
env:
  CI: ""

on:
  push:
    branches: [ "main", "workflow" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    # change "homepage" in package.json with current repository name
    - run: touch repository.txt
    - run: echo ${{ github.repository }} >> repository.txt
    - run: sed -i 's/.*\///' repository.txt
    - run: |
        sed -i "s/homepage.*/homepage\": \"$(sed 's@[/\&]@\\&@g;$!s/$/\\/' repository.txt)\",/g" package.json
    - run: rm repository.txt
    - name: Build
      run: |
        npm install
        npm run build
        echo ${{ secrets.REACT_APP_SECRET }}
      env:
        REACT_APP_firebase_apiKey: ${{ secrets.REACT_APP_FIREBASE_APIKEY }}
        REACT_APP_firebase_appId: ${{ secrets.REACT_APP_FIREBASE_APPID }}
        REACT_APP_firebase_messagingSenderId: ${{ secrets.REACT_APP_FIREBASE_MESSAGINGSENDERID }}
        REACT_APP_firebase_measurementId: ${{ secrets.REACT_APP_FIREBASE_MEASUREMENTID }}
        REACT_APP_firebase_databaseURL: ${{ secrets.REACT_APP_FIREBASE_DATABASEURL }}
        REACT_APP_SECRET: ${{ secrets.REACT_APP_SECRET }}
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
